//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "coursegroup_course")]
pub struct Model {
    pub coursegroup_id: i32,
    pub course_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::coursegroup::Entity",
        from = "Column::CoursegroupId",
        to = "super::coursegroup::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Coursegroup,
    #[sea_orm(
        belongs_to = "super::course::Entity",
        from = "Column::CourseId",
        to = "super::course::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Course,
}

impl Related<super::coursegroup::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Coursegroup.def()
    }
}

impl Related<super::course::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Course.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
