//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "review")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Custom(\"LONGTEXT\".to_owned())")]
    pub title: String,
    #[sea_orm(column_type = "Custom(\"LONGTEXT\".to_owned())")]
    pub content: String,
    pub history: Json,
    pub reviewer_id: i32,
    pub time_created: DateTime,
    pub time_updated: DateTime,
    pub rank: Json,
    pub upvoters: Json,
    pub downvoters: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::course_review::Entity")]
    CourseReview,
}

impl Related<super::course_review::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CourseReview.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
