//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;
use sea_orm::entity::FromQueryResult;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize, DeriveEntityModel)]
#[sea_orm(table_name = "review")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Custom(\"LONGTEXT\".to_owned())")]
    pub title: String,
    #[sea_orm(column_type = "Custom(\"LONGTEXT\".to_owned())")]
    pub content: String,
    pub history: Json,
    pub reviewer_id: i32,
    pub time_created: DateTime,
    pub time_updated: DateTime,
    pub rank: Json,
    pub upvoters: Json,
    pub downvoters: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::course::Entity")]
    Course,
}

impl Related<super::course::Entity> for Entity {
    fn to() -> RelationDef {
        super::course_review::Relation::Course.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::course_review::Relation::Review.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
