name: Publish to Docker - Development

on:
  push:
    branches: [dev]

env:
  APP_NAME: cb_backend_next

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: Remove mirror configs
        run: rm -rf .cargo
      - name: Get tag version
        id: tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:dev
      - name: Deploy
        run: curl -X POST ${{ secrets.DEPLOY_WEBHOOK_DEV }}
