//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::course::Entity as Course;
pub use super::coursegroup::Entity as Coursegroup;
pub use super::review::Entity as Review;
pub use super::achievement::Entity as Achievement;
pub use super::user_achievement::Entity as UserAchievement;
